# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-28 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataEntryEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeCode', models.CharField(max_length=50)),
                ('numberDataInput', models.IntegerField()),
                ('dataUniqueIdList', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=None, max_length=50)),
                ('villageName', models.CharField(default=None, max_length=500)),
                ('villageCode', models.CharField(default=None, max_length=50)),
                ('shreni', models.CharField(choices=[('4', 'Shreni Four'), ('5', 'Shreni Five'), ('6', 'Shreni Six')], max_length=100)),
                ('distanceRoad', models.FloatField(default=None)),
                ('gataNumber', models.IntegerField(default=None)),
                ('area', models.IntegerField(default=None)),
                ('connectivity', models.BooleanField()),
                ('allotted', models.BooleanField(default=False)),
                ('latitudeCoordinate', models.CharField(default=None, max_length=15)),
                ('longitudeCoordinate', models.CharField(default=None, max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('image1', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('image2', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('uniqueId', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
